"use client"

import type { Metadata } from "next";
import NavBar from "@/app/component/navBar_editor"
import { Geist, Geist_Mono } from "next/font/google"
import "@/app/globals.css"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });
  
  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });
  
  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

export default function Template({ children }: { children: React.ReactNode }) {
    return (
        <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <NavBar></NavBar>
            <div>{children}</div>
        </div>
    )
  }